### ISSUE TITLE
problem with CSS class: level-bar-inner

### ISSUE THREAD

**Issue by DamienAllonsius** [xriley/Developer-Theme#7]
Hi ! 
my webpage follows your template
https://damienallonsius.github.io/
and the `level-bar-inner` class is not correctly displayed (see the programming skills section on the right) whereas everything is fine when I open the index.html file with firefox. Actually, on the previous link, the bars are displayed randomly (if you refresh the page 10 times, you will see the green level appearing once or twice).
Any idea of the source of the problem ?

Cheers

PS: the problem seems to disappear when I disable the module [dark reader](https://darkreader.org/) on firefox.

**Comment by ailsamm** [comment]
Hi @xriley , is there a fix for this? I'm also having this issue. @DamienAllonsius is correct - the issue only seems to be present when dark mode is activated, otherwise it works as expected. Thanks!

**Comment by ailsamm** [comment]
I found the solution by analysing @DamienAllonsius 's page (thanks for this! :) )
So, in case anyone else is having the issue, here is the solution:
It is necessary to change the **width** of the <div> element of class _level-bar-inner_ to the percentage (not px) that you wish. You must also ensure that the data-level is equal to the width. For instance, this div could look like this:
`<div class="level-bar-inner" data-level="90%" style="width: 90%;">`

**Comment by DamienAllonsius** [comment]
Hi @ailsamm Thanks for your help.
I've tried to add the `style="width: 90%;" ` as you suggested. However the problem seems to persist :disappointed: Any other idea ?

**Comment by xriley** [comment]
FYI @ailsamm and @DamienAllonsius - https://github.com/jquery/jquery/issues/3194
